export default [
  {
    id: 1,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 2,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 3,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 4,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 5,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 6,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 7,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 8,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 9,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 10,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 11,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 12,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 13,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 14,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 15,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 16,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 17,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  }, {
    id: 18,
    name: 'Tiger Nixon',
    position: 'System Architect',
    city: 'Edinburgh',
    age: '61',
    createdAt: '2011/04/25',
    salary: '$320,800',
    image: 'img/theme/team-1.jpg',
    product: 'cashflash Dashboard PRO',
    active: true,
  },
];
